package com.neuedu.dao;

import com.neuedu.entity.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    int checkUsername(String username);

    int checkEmail(String email);

    User selectByusernameAndpassword(@Param("username") String username, @Param("password") String password);

    // 根据用户名查询问题
    String selectQuestionByUsername(String username);
    // 校验答案
    int checkAnswerByUsernameAndQuestion(@Param("username") String username,@Param("question") String question,@Param("answer") String answer);
    // 根据用户名更新密码
    int updatePasswordByUsername(@Param("username") String username,@Param("password") String passwordNew);








}