package com.neuedu.entity;

import java.util.Date;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.aname
     *
     * @mbg.generated
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.aphone
     *
     * @mbg.generated
     */
    private String aphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.amobile
     *
     * @mbg.generated
     */
    private String amobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.aprovince
     *
     * @mbg.generated
     */
    private String aprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.acity
     *
     * @mbg.generated
     */
    private String acity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.adistrict
     *
     * @mbg.generated
     */
    private String adistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.azip
     *
     * @mbg.generated
     */
    private String azip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.uid
     *
     * @return the value of address.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.uid
     *
     * @param uid the value for address.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.aname
     *
     * @return the value of address.aname
     *
     * @mbg.generated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.aname
     *
     * @param aname the value for address.aname
     *
     * @mbg.generated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.aphone
     *
     * @return the value of address.aphone
     *
     * @mbg.generated
     */
    public String getAphone() {
        return aphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.aphone
     *
     * @param aphone the value for address.aphone
     *
     * @mbg.generated
     */
    public void setAphone(String aphone) {
        this.aphone = aphone == null ? null : aphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.amobile
     *
     * @return the value of address.amobile
     *
     * @mbg.generated
     */
    public String getAmobile() {
        return amobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.amobile
     *
     * @param amobile the value for address.amobile
     *
     * @mbg.generated
     */
    public void setAmobile(String amobile) {
        this.amobile = amobile == null ? null : amobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.aprovince
     *
     * @return the value of address.aprovince
     *
     * @mbg.generated
     */
    public String getAprovince() {
        return aprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.aprovince
     *
     * @param aprovince the value for address.aprovince
     *
     * @mbg.generated
     */
    public void setAprovince(String aprovince) {
        this.aprovince = aprovince == null ? null : aprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.acity
     *
     * @return the value of address.acity
     *
     * @mbg.generated
     */
    public String getAcity() {
        return acity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.acity
     *
     * @param acity the value for address.acity
     *
     * @mbg.generated
     */
    public void setAcity(String acity) {
        this.acity = acity == null ? null : acity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.adistrict
     *
     * @return the value of address.adistrict
     *
     * @mbg.generated
     */
    public String getAdistrict() {
        return adistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.adistrict
     *
     * @param adistrict the value for address.adistrict
     *
     * @mbg.generated
     */
    public void setAdistrict(String adistrict) {
        this.adistrict = adistrict == null ? null : adistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.azip
     *
     * @return the value of address.azip
     *
     * @mbg.generated
     */
    public String getAzip() {
        return azip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.azip
     *
     * @param azip the value for address.azip
     *
     * @mbg.generated
     */
    public void setAzip(String azip) {
        this.azip = azip == null ? null : azip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.createtime
     *
     * @return the value of address.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.createtime
     *
     * @param createtime the value for address.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.updatetime
     *
     * @return the value of address.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.updatetime
     *
     * @param updatetime the value for address.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}