package com.neuedu.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.onum
     *
     * @mbg.generated
     */
    private Long onum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.pay
     *
     * @mbg.generated
     */
    private BigDecimal pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.paytype
     *
     * @mbg.generated
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.addressid
     *
     * @mbg.generated
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.postage
     *
     * @mbg.generated
     */
    private Integer postage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.paytime
     *
     * @mbg.generated
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.sendtime
     *
     * @mbg.generated
     */
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.closetime
     *
     * @mbg.generated
     */
    private Date closetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.endtime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.id
     *
     * @return the value of ordertable.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.id
     *
     * @param id the value for ordertable.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.onum
     *
     * @return the value of ordertable.onum
     *
     * @mbg.generated
     */
    public Long getOnum() {
        return onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.onum
     *
     * @param onum the value for ordertable.onum
     *
     * @mbg.generated
     */
    public void setOnum(Long onum) {
        this.onum = onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.uid
     *
     * @return the value of ordertable.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.uid
     *
     * @param uid the value for ordertable.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.pay
     *
     * @return the value of ordertable.pay
     *
     * @mbg.generated
     */
    public BigDecimal getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.pay
     *
     * @param pay the value for ordertable.pay
     *
     * @mbg.generated
     */
    public void setPay(BigDecimal pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.paytype
     *
     * @return the value of ordertable.paytype
     *
     * @mbg.generated
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.paytype
     *
     * @param paytype the value for ordertable.paytype
     *
     * @mbg.generated
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.status
     *
     * @return the value of ordertable.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.status
     *
     * @param status the value for ordertable.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.addressid
     *
     * @return the value of ordertable.addressid
     *
     * @mbg.generated
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.addressid
     *
     * @param addressid the value for ordertable.addressid
     *
     * @mbg.generated
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.postage
     *
     * @return the value of ordertable.postage
     *
     * @mbg.generated
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.postage
     *
     * @param postage the value for ordertable.postage
     *
     * @mbg.generated
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.paytime
     *
     * @return the value of ordertable.paytime
     *
     * @mbg.generated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.paytime
     *
     * @param paytime the value for ordertable.paytime
     *
     * @mbg.generated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.sendtime
     *
     * @return the value of ordertable.sendtime
     *
     * @mbg.generated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.sendtime
     *
     * @param sendtime the value for ordertable.sendtime
     *
     * @mbg.generated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.closetime
     *
     * @return the value of ordertable.closetime
     *
     * @mbg.generated
     */
    public Date getClosetime() {
        return closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.closetime
     *
     * @param closetime the value for ordertable.closetime
     *
     * @mbg.generated
     */
    public void setClosetime(Date closetime) {
        this.closetime = closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.endtime
     *
     * @return the value of ordertable.endtime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.endtime
     *
     * @param endtime the value for ordertable.endtime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.createtime
     *
     * @return the value of ordertable.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.createtime
     *
     * @param createtime the value for ordertable.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.updatetime
     *
     * @return the value of ordertable.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.updatetime
     *
     * @param updatetime the value for ordertable.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}