package com.neuedu.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Orderitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.onum
     *
     * @mbg.generated
     */
    private Long onum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.productid
     *
     * @mbg.generated
     */
    private Integer productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.productname
     *
     * @mbg.generated
     */
    private String productname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.productimage
     *
     * @mbg.generated
     */
    private String productimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.currentprice
     *
     * @mbg.generated
     */
    private BigDecimal currentprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.totalprice
     *
     * @mbg.generated
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.id
     *
     * @return the value of orderitem.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.id
     *
     * @param id the value for orderitem.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.onum
     *
     * @return the value of orderitem.onum
     *
     * @mbg.generated
     */
    public Long getOnum() {
        return onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.onum
     *
     * @param onum the value for orderitem.onum
     *
     * @mbg.generated
     */
    public void setOnum(Long onum) {
        this.onum = onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.uid
     *
     * @return the value of orderitem.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.uid
     *
     * @param uid the value for orderitem.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.productid
     *
     * @return the value of orderitem.productid
     *
     * @mbg.generated
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.productid
     *
     * @param productid the value for orderitem.productid
     *
     * @mbg.generated
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.productname
     *
     * @return the value of orderitem.productname
     *
     * @mbg.generated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.productname
     *
     * @param productname the value for orderitem.productname
     *
     * @mbg.generated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.productimage
     *
     * @return the value of orderitem.productimage
     *
     * @mbg.generated
     */
    public String getProductimage() {
        return productimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.productimage
     *
     * @param productimage the value for orderitem.productimage
     *
     * @mbg.generated
     */
    public void setProductimage(String productimage) {
        this.productimage = productimage == null ? null : productimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.currentprice
     *
     * @return the value of orderitem.currentprice
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentprice() {
        return currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.currentprice
     *
     * @param currentprice the value for orderitem.currentprice
     *
     * @mbg.generated
     */
    public void setCurrentprice(BigDecimal currentprice) {
        this.currentprice = currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.quantity
     *
     * @return the value of orderitem.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.quantity
     *
     * @param quantity the value for orderitem.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.totalprice
     *
     * @return the value of orderitem.totalprice
     *
     * @mbg.generated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.totalprice
     *
     * @param totalprice the value for orderitem.totalprice
     *
     * @mbg.generated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.createtime
     *
     * @return the value of orderitem.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.createtime
     *
     * @param createtime the value for orderitem.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.updatetime
     *
     * @return the value of orderitem.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.updatetime
     *
     * @param updatetime the value for orderitem.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}