package com.neuedu.entity;

import java.util.Date;

public class Payinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.onum
     *
     * @mbg.generated
     */
    private Long onum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.pay
     *
     * @mbg.generated
     */
    private Integer pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.paystatus
     *
     * @mbg.generated
     */
    private String paystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.id
     *
     * @return the value of payinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.id
     *
     * @param id the value for payinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.onum
     *
     * @return the value of payinfo.onum
     *
     * @mbg.generated
     */
    public Long getOnum() {
        return onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.onum
     *
     * @param onum the value for payinfo.onum
     *
     * @mbg.generated
     */
    public void setOnum(Long onum) {
        this.onum = onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.uid
     *
     * @return the value of payinfo.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.uid
     *
     * @param uid the value for payinfo.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.pay
     *
     * @return the value of payinfo.pay
     *
     * @mbg.generated
     */
    public Integer getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.pay
     *
     * @param pay the value for payinfo.pay
     *
     * @mbg.generated
     */
    public void setPay(Integer pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.paystatus
     *
     * @return the value of payinfo.paystatus
     *
     * @mbg.generated
     */
    public String getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.paystatus
     *
     * @param paystatus the value for payinfo.paystatus
     *
     * @mbg.generated
     */
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus == null ? null : paystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.number
     *
     * @return the value of payinfo.number
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.number
     *
     * @param number the value for payinfo.number
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.createtime
     *
     * @return the value of payinfo.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.createtime
     *
     * @param createtime the value for payinfo.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.updatetime
     *
     * @return the value of payinfo.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.updatetime
     *
     * @param updatetime the value for payinfo.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}